# Exported from:        http://release-nightly.devops.dev.digitalai.cloud/
# Release version:      25.3.0-beta.404
# Date created:         Fri Apr 04 09:53:16 GMT 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Configure Release.yaml
  - "Template_Deployment pattern: Blue Green.yaml"
  - "Template_Deployment pattern: Canary Release.yaml"
  - Template_Guided Tour for Release Managers.yaml
  - Template_Sample Release Template with Digital.ai Deploy.yaml
  - Template_Sample Release Template.yaml
  - Template_Welcome to Release!.yaml
